name: Pester Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ 'feature/*', 'enhancement/*', 'bug/*', 'dev' ]

jobs:
  build:
    uses: ./.github/workflows/ci-ps-shared-build.yml

  install-module:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - name: Get Build Run Id
        id: getRunId
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh auth login --with-token $env:GITHUB_TOKEN
          $RunId = gh run list --workflow ci-ps-build.yml --repo plaplain/PSMinecraftServerManager --status success --limit 1 --jq '[.[] | select(.conclusion=="success")] | .[0].databaseId' --json databaseId,conclusion
          "run_id=$runId" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
      - name: Download Module Artifact
        uses: actions/download-artifact@v8
        with:
          github-token: ${{ github.token }}
          run-id: ${{ steps.getRunId.outputs.run_id }}
          name: PSMinecraftServerManager
          path: ${{ runner.temp }}\MinecraftServerManager

      - name: Install Module
        shell: pwsh
        run: |
          Import-Module "${{ runner.temp }}\MinecraftServerManager\MinecraftServerManager.psd1"
  tests-windows:
    needs: install-module
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Unit Tests
      id: UnitTests
      shell: pwsh
      run: |
        .\tools\pester.ps1 -Tags "Integration" -TestPath "${{ github.workspace }}\tests" -CodePath "${{ github.workspace }}\src"
  tests-linux:
    needs: install-module
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Unit Tests
      id: UnitTests
      shell: pwsh
      run: |
        .\tools\pester.ps1 -Tags "Unit" -Integration "${{ github.workspace }}\tests" -CodePath "${{ github.workspace }}\src"
