name: Pester Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ 'feature/*', 'enhancement/*', 'bug/*', 'dev' ]

jobs:
  build-windows:
    uses: ./.github/workflows/ci-ps-shared-build.yml
    with:
      runsOn: 'windows-latest'

  build-linux:
    uses: ./.github/workflows/ci-ps-shared-build.yml
    with:
      runsOn: 'ubuntu-latest'

  tests-windows:
    uses: './.github/workflows/ci-ps-shared-pester.yml'
    needs: build-windows
    with:
      runsOn: 'windows-latest'
      testType: 'integration'
      artifactPath: '${{ github.workspace }}/temp'
      
  tests-linux:
    uses: './.github/workflows/ci-ps-shared-pester.yml'
    needs: build-linux
    with:
      runsOn: 'ubuntu-latest'
      testType: 'integration'
      artifactPath: '${{ github.workspace }}/temp'
