# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# https://github.com/microsoft/action-psscriptanalyzer
# For more information on PSScriptAnalyzer in general, see
# https://github.com/PowerShell/PSScriptAnalyzer

name: PSScriptAnalyzer

on:
  workflow_dispatch: 
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" , "dev" ]
  schedule:
    - cron: '33 1 * * 6'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:      
    - name: Run PSScriptAnalyzer and ConvertToSARIF
      shell: pwsh
      run: |
        $analyzerModule = Get-Module -ListAvailable -Name PSScriptAnalyzer
        if ($null -eq $analyzerModule) {
          Install-Module -Name PSScriptAnalyzer -Force
          Get-Module -ListAvailable -Name PSScriptAnalyzer
        }
        
        $sarifModule = Get-Module -ListAvailable -Name ConvertToSARIF
        if ($null -eq $sarifModule) {
          Install-Module -Name ConvertToSARIF -Force
        }
        Import-Module -Name ConvertToSARIF -Force
        
        $htPSA = [ordered]@{ Path = '/home/runner/work/PSMinecraftServerManager/PSMinecraftServerManager'; }
        Write-Output "Modules installed, now running tests."
        if(![string]::IsNullOrEmpty('')) { $htPSA.add('CustomRulePath', @()) }
        if(![string]::IsNullOrEmpty('')) { $htPSA.add('RecurseCustomRulePath', $true) }
        if(![string]::IsNullOrEmpty('')) { $htPSA.add('ExcludeRule', @()) }
        if(![string]::IsNullOrEmpty('') -and '' -ne 'false') { $htPSA.add('IncludeDefaultRules', $true) }
        if(![string]::IsNullOrEmpty('')) { $htPSA.add('IncludeRule', @()) }
        if(![string]::IsNullOrEmpty('"Error", "Warning"')) { $htPSA.add('Severity', @("Error", "Warning")) }
        if(![string]::IsNullOrEmpty('true') -and '' -ne 'false') { $htPSA.add('Recurse', $true) }
        if(![string]::IsNullOrEmpty('')) { $htPSA.add('Fix', $true) }
        if(![string]::IsNullOrEmpty('')) { $htPSA.add('EnableExit', $true) }
        if(![string]::IsNullOrEmpty('')) { $htPSA.add('Settings', '') }
        $htCTS = [ordered]@{ FilePath = '/home/runner/work/results.sarif'; }
        if(![string]::IsNullOrEmpty('')) { $htCTS.add('IgnorePattern', '') }
        Invoke-ScriptAnalyzer @htPSA | ConvertTo-SARIF @htCTS
        #$ScriptAnalysis =Invoke-ScriptAnalyzer @htPSA
        Write-Output "Results: $($ScriptAnalysis | Out-String)"
        Write-Output "Script Analyzer completed."

    - uses: actions/checkout@v4
#
#      - name: Run PSScriptAnalyzer
#        uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
#        with:
#          severity: '"Error", "Warning"'
#          # Check https://github.com/microsoft/action-psscriptanalyzer for more info about the options.
#          # The below set up runs PSScriptAnalyzer to your entire repository and runs some basic security rules.
#          path: ${{ github.workspace }}
#          recurse: true
#          # Include your own basic security rules. Removing this option will run all the rules
#          #includeRule: '"PSAvoidGlobalAliases", "PSAvoidUsingConvertToSecureStringWithPlainText"'
#          output: results.sarif
#
      # Upload the SARIF file generated in the previous step
    - name: Upload SARIF results file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: /home/runner/work/results.sarif