name: Pester Smoke Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ 'feature/*', 'enhancement/*', 'bug/*', 'dev' ]

jobs:
  build:
    uses: ./.github/workflows/ci-ps-shared-build.yml
    with:
      runsOn: 'windows-latest'
  tests-windows:
    uses: './.github/workflows/ci-ps-shared-pester.yml'
    needs: build
    with:
      runsOn: 'windows-latest'
      testType: 'smoke'
      
  tests-linux:
    uses: './.github/workflows/ci-ps-shared-pester.yml'
    needs: build
    with:
      runsOn: 'ubuntu-latest'
      testType: 'smoke'
